import { Preset, AnimationSettings } from './types';

export const defaultSettings: AnimationSettings = {
  backgroundColor: '#0a0a0f',
  backgroundGradient: true,
  backgroundGradientColor: '#1a0a2e',
  geometryType: 'torusKnot',
  shapeCount: 1,
  shapeScale: 1,
  shapeColor: '#8b5cf6',
  shapeColor2: '#06b6d4',
  useGradientMaterial: true,
  wireframe: false,
  metalness: 0.8,
  roughness: 0.2,
  geometryDetail: 1,
  reflectionsEnabled: true,
  // 3D Text
  textContent: 'HELLO',
  textFont: 'helvetiker_bold',
  textDepth: 0.3,
  textBevel: true,
  textBevelThickness: 0.03,
  textBevelSize: 0.02,
  animationType: 'orbit',
  loopDuration: 4,
  speed: 1,
  amplitude: 1,
  spread: 2,
  frequency: 1,
  phaseOffset: 0,
  verticalAmplitude: 1,
  horizontalAmplitude: 1,
  rotationMultiplier: 1,
  rotationAxis: 'y',
  cameraDistance: 6,
  cameraAutoRotate: false,
  cameraAutoRotateSpeed: 1,
  cameraPreset: 'custom',
  // Render modes - ASCII
  asciiEnabled: false,
  asciiCharset: 'standard',
  asciiResolution: 60,
  asciiOpacity: 1,
  asciiBackgroundOpacity: 1,
  asciiTextColor: '#00ff00',
  asciiFontSize: 12,
  asciiFontWeight: 'bold',
  asciiInvert: false,
  asciiContrast: 1.2,
  asciiGamma: 1.0,
  asciiColorMode: true,
  asciiBrightnessBoost: 1.0,
  // Dithering & Palette Effects
  ditheringEnabled: false,
  ditheringType: 'bayer',
  ditheringIntensity: 0.3,
  ditheringResolution: 0.2,
  paletteType: 'full',
  pixelationEnabled: false,
  pixelSize: 4,
  exportWidth: 1080,
  exportHeight: 1080,
  exportFps: 60,
  exportFormat: 'webm',
  exportQuality: 'excellent',
  exportLoopCount: 1,
  seamlessLoopVerification: true,
};

export const presets: Preset[] = [
  {
    id: 'simple-torus-rotation',
    name: 'Simple Torus Rotation',
    description: 'Clean torus with simple Y-axis rotation',
    thumbnail: '🔄',
    settings: {
      geometryType: 'torus',
      shapeCount: 1,
      shapeScale: 1.2,
      geometryDetail: 6,
      shapeColor: '#8b5cf6',
      shapeColor2: '#06b6d4',
      animationType: 'simpleRotation',
      rotationAxis: 'y',
      loopDuration: 4,
      cameraPreset: 'front',
      cameraDistance: 5,
      metalness: 0.7,
      roughness: 0.3,
      backgroundColor: '#0a0a0f',
      backgroundGradientColor: '#1a0a2e',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'cosmic-torus',
    name: 'Cosmic Torus',
    description: 'A glowing torus knot orbiting in space',
    thumbnail: '🌀',
    settings: {
      geometryType: 'torusKnot',
      shapeCount: 1,
      shapeColor: '#8b5cf6',
      shapeColor2: '#ec4899',
      animationType: 'orbit',
      loopDuration: 4,
      metalness: 0.9,
      roughness: 0.1,
      backgroundColor: '#05050f',
      backgroundGradientColor: '#0f0520',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'sacred-geometry',
    name: 'Sacred Geometry',
    description: 'Breathing icosahedrons in harmony',
    thumbnail: '💎',
    settings: {
      geometryType: 'icosahedron',
      shapeCount: 5,
      shapeColor: '#f59e0b',
      shapeColor2: '#ef4444',
      animationType: 'breathe',
      loopDuration: 3,
      wireframe: true,
      metalness: 0.5,
      roughness: 0.5,
      amplitude: 1.2,
      spread: 3,
      backgroundColor: '#0a0505',
      backgroundGradientColor: '#1a0a05',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'neon-spiral',
    name: 'Neon Spiral',
    description: 'Cubes spiraling into infinity',
    thumbnail: '🔮',
    settings: {
      geometryType: 'cube',
      shapeCount: 12,
      shapeScale: 0.6,
      shapeColor: '#06d6a0',
      shapeColor2: '#118ab2',
      animationType: 'spiral',
      loopDuration: 5,
      speed: 1,
      spread: 4,
      backgroundColor: '#020a08',
      backgroundGradientColor: '#051a15',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'crystal-wave',
    name: 'Crystal Wave',
    description: 'Octahedrons riding a wave',
    thumbnail: '🌊',
    settings: {
      geometryType: 'octahedron',
      shapeCount: 8,
      shapeScale: 0.5,
      shapeColor: '#3b82f6',
      shapeColor2: '#a855f7',
      animationType: 'wave',
      loopDuration: 3,
      amplitude: 1.5,
      spread: 5,
      backgroundColor: '#050510',
      backgroundGradientColor: '#0a0a25',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'supernova',
    name: 'Supernova',
    description: 'Shapes exploding and reforming',
    thumbnail: '💥',
    settings: {
      geometryType: 'tetrahedron',
      shapeCount: 16,
      shapeScale: 0.4,
      shapeColor: '#f97316',
      shapeColor2: '#eab308',
      animationType: 'explode',
      loopDuration: 4,
      amplitude: 2,
      spread: 1,
      backgroundColor: '#0a0500',
      backgroundGradientColor: '#1a0f00',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'minimalist-sphere',
    name: 'Minimalist Sphere',
    description: 'Clean, elegant sphere animation',
    thumbnail: '⚪',
    settings: {
      geometryType: 'sphere',
      shapeCount: 1,
      shapeScale: 1.5,
      shapeColor: '#ffffff',
      shapeColor2: '#94a3b8',
      animationType: 'breathe',
      loopDuration: 3,
      metalness: 1,
      roughness: 0,
      wireframe: false,
      backgroundColor: '#0f172a',
      backgroundGradientColor: '#1e293b',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'matrix-cascade',
    name: 'Matrix Cascade',
    description: 'Shapes cascading like digital rain',
    thumbnail: '🟩',
    settings: {
      geometryType: 'cube',
      shapeCount: 20,
      shapeScale: 0.3,
      shapeColor: '#22c55e',
      shapeColor2: '#15803d',
      animationType: 'cascade',
      loopDuration: 4,
      speed: 1,
      spread: 5,
      wireframe: true,
      backgroundColor: '#000a00',
      backgroundGradientColor: '#001a00',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'vortex-storm',
    name: 'Vortex Storm',
    description: 'A mesmerizing vortex of shapes',
    thumbnail: '🌪️',
    settings: {
      geometryType: 'dodecahedron',
      shapeCount: 10,
      shapeScale: 0.5,
      shapeColor: '#e11d48',
      shapeColor2: '#7c3aed',
      animationType: 'vortex',
      loopDuration: 5,
      speed: 1,
      amplitude: 1.5,
      spread: 3,
      backgroundColor: '#0a0005',
      backgroundGradientColor: '#15000a',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'pendulum-zen',
    name: 'Pendulum Zen',
    description: 'Peaceful pendulum-like motion',
    thumbnail: '🕐',
    settings: {
      geometryType: 'cylinder',
      shapeCount: 7,
      shapeScale: 0.4,
      shapeColor: '#f0abfc',
      shapeColor2: '#c084fc',
      animationType: 'pendulum',
      loopDuration: 4,
      amplitude: 1.3,
      spread: 4,
      backgroundColor: '#0a0010',
      backgroundGradientColor: '#150020',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'kaleidoscope-dream',
    name: 'Kaleidoscope',
    description: 'Mesmerizing kaleidoscope pattern',
    thumbnail: '🎭',
    settings: {
      geometryType: 'cone',
      shapeCount: 12,
      shapeScale: 0.5,
      shapeColor: '#fb923c',
      shapeColor2: '#f472b6',
      animationType: 'kaleidoscope',
      loopDuration: 6,
      speed: 1,
      spread: 3,
      backgroundColor: '#050005',
      backgroundGradientColor: '#100010',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'ring-dance',
    name: 'Ring Dance',
    description: 'Elegant rings orbiting in harmony',
    thumbnail: '⭕',
    settings: {
      geometryType: 'ring',
      shapeCount: 5,
      shapeScale: 0.8,
      shapeColor: '#a78bfa',
      shapeColor2: '#60a5fa',
      animationType: 'wave',
      loopDuration: 4,
      amplitude: 1,
      spread: 3,
      backgroundColor: '#0a0015',
      backgroundGradientColor: '#1a0030',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'pyramid-stack',
    name: 'Pyramid Stack',
    description: 'Pyramids stacking in mystical rhythm',
    thumbnail: '△',
    settings: {
      geometryType: 'pyramid',
      shapeCount: 8,
      shapeScale: 0.6,
      shapeColor: '#fbbf24',
      shapeColor2: '#f97316',
      animationType: 'explode',
      loopDuration: 5,
      amplitude: 2,
      spread: 2,
      backgroundColor: '#0a0500',
      backgroundGradientColor: '#1a0f00',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'plane-cascade',
    name: 'Plane Cascade',
    description: 'Planes cascading in digital flow',
    thumbnail: '◻️',
    settings: {
      geometryType: 'plane',
      shapeCount: 12,
      shapeScale: 0.5,
      shapeColor: '#34d399',
      shapeColor2: '#10b981',
      animationType: 'cascade',
      loopDuration: 4,
      speed: 1,
      spread: 4,
      backgroundColor: '#000a05',
      backgroundGradientColor: '#001505',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'prism-geometry',
    name: 'Prism Geometry',
    description: 'Crystalline prisms breathing in 3D',
    thumbnail: '🔷',
    settings: {
      geometryType: 'prism',
      shapeCount: 6,
      shapeScale: 0.7,
      shapeColor: '#c084fc',
      shapeColor2: '#e879f9',
      animationType: 'breathe',
      loopDuration: 3.5,
      amplitude: 1.5,
      spread: 3,
      metalness: 0.7,
      roughness: 0.3,
      backgroundColor: '#0a0010',
      backgroundGradientColor: '#150025',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'sphere-trance',
    name: 'Sphere Trance',
    description: 'Hypnotic spiral of glowing spheres',
    thumbnail: '●',
    settings: {
      geometryType: 'sphere',
      shapeCount: 9,
      shapeScale: 0.6,
      shapeColor: '#ec4899',
      shapeColor2: '#f43f5e',
      animationType: 'spiral',
      loopDuration: 5,
      speed: 1,
      amplitude: 1.2,
      spread: 3.5,
      backgroundColor: '#05000a',
      backgroundGradientColor: '#0f0015',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'morphing-abyss',
    name: 'Morphing Abyss',
    description: 'Shapes morph through dimensional space',
    thumbnail: '🌀',
    settings: {
      geometryType: 'dodecahedron',
      shapeCount: 4,
      shapeScale: 1,
      shapeColor: '#7c3aed',
      shapeColor2: '#3b82f6',
      animationType: 'morph',
      loopDuration: 6,
      speed: 1,
      amplitude: 1.5,
      spread: 2.5,
      backgroundColor: '#050010',
      backgroundGradientColor: '#0a001a',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'cube-rotation',
    name: 'Cube Maze',
    description: 'Cubes rotating through infinite maze',
    thumbnail: '🎲',
    settings: {
      geometryType: 'cube',
      shapeCount: 15,
      shapeScale: 0.4,
      shapeColor: '#06d6a0',
      shapeColor2: '#13b0f5',
      animationType: 'kaleidoscope',
      loopDuration: 5,
      speed: 1,
      spread: 3,
      wireframe: true,
      backgroundColor: '#000805',
      backgroundGradientColor: '#001005',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'zen-pendulum',
    name: 'Zen Pendulum',
    description: 'Peaceful swaying of prismatic forms',
    thumbnail: '⛩️',
    settings: {
      geometryType: 'prism',
      shapeCount: 5,
      shapeScale: 0.8,
      shapeColor: '#fca5a5',
      shapeColor2: '#fb7185',
      animationType: 'pendulum',
      loopDuration: 4,
      amplitude: 1.2,
      spread: 2.5,
      metalness: 0.5,
      roughness: 0.6,
      backgroundColor: '#0a0005',
      backgroundGradientColor: '#150a0a',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'ascii-retro',
    name: 'ASCII Retro',
    description: 'Large, bold ASCII characters with retro styling',
    thumbnail: '💻',
    settings: {
      geometryType: 'cube',
      shapeCount: 12,
      shapeScale: 0.8,
      shapeColor: '#00ff00',
      shapeColor2: '#ffffff',
      animationType: 'orbit',
      loopDuration: 4,
      speed: 1,
      amplitude: 1,
      spread: 4,
      backgroundColor: '#000000',
      backgroundGradient: false,
      asciiEnabled: true,
      asciiCharset: 'blocks',
      asciiResolution: 80,
      asciiFontSize: 24,
      asciiFontWeight: 'bold',
      asciiOpacity: 1,
      asciiBackgroundOpacity: 1,
      asciiColorMode: true,
      asciiContrast: 1.5,
      asciiGamma: 0.8,
      asciiBrightnessBoost: 1.5,
      asciiInvert: false,
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'bounce-party',
    name: 'Bounce Party',
    description: 'Shapes bouncing in joyful rhythm',
    thumbnail: '🏀',
    settings: {
      geometryType: 'sphere',
      shapeCount: 8,
      shapeScale: 0.6,
      shapeColor: '#fbbf24',
      shapeColor2: '#f59e0b',
      animationType: 'bounce',
      loopDuration: 3,
      speed: 1,
      amplitude: 1.5,
      verticalAmplitude: 2,
      horizontalAmplitude: 1,
      spread: 4,
      frequency: 2,
      backgroundColor: '#0a0500',
      backgroundGradientColor: '#1a0f00',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'twist-dream',
    name: 'Twist Dream',
    description: 'Twisting shapes in hypnotic motion',
    thumbnail: '🌀',
    settings: {
      geometryType: 'torusKnot',
      shapeCount: 3,
      shapeScale: 0.8,
      shapeColor: '#a855f7',
      shapeColor2: '#c084fc',
      animationType: 'twist',
      loopDuration: 4,
      speed: 1,
      amplitude: 1.2,
      verticalAmplitude: 1.5,
      horizontalAmplitude: 1.8,
      spread: 3,
      frequency: 1.5,
      backgroundColor: '#0a0010',
      backgroundGradientColor: '#150020',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'pulse-wave',
    name: 'Pulse Wave',
    description: 'Pulsing cubes in wave formation',
    thumbnail: '💓',
    settings: {
      geometryType: 'cube',
      shapeCount: 10,
      shapeScale: 0.5,
      shapeColor: '#06b6d4',
      shapeColor2: '#0891b2',
      animationType: 'pulse',
      loopDuration: 3.5,
      speed: 1,
      amplitude: 1.8,
      verticalAmplitude: 1.2,
      horizontalAmplitude: 1.5,
      spread: 5,
      frequency: 2.5,
      backgroundColor: '#020a08',
      backgroundGradientColor: '#051a15',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'figure8-flow',
    name: 'Figure 8 Flow',
    description: 'Elegant figure-8 motion patterns',
    thumbnail: '∞',
    settings: {
      geometryType: 'icosahedron',
      shapeCount: 6,
      shapeScale: 0.7,
      shapeColor: '#ec4899',
      shapeColor2: '#f97316',
      animationType: 'figure8',
      loopDuration: 5,
      speed: 1,
      amplitude: 1.3,
      verticalAmplitude: 1.6,
      horizontalAmplitude: 2,
      spread: 3.5,
      frequency: 1,
      backgroundColor: '#0a0005',
      backgroundGradientColor: '#1a000f',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'helix-spiral',
    name: 'Helix Spiral',
    description: 'DNA-like helical motion',
    thumbnail: '🧬',
    settings: {
      geometryType: 'cylinder',
      shapeCount: 12,
      shapeScale: 0.4,
      shapeColor: '#10b981',
      shapeColor2: '#059669',
      animationType: 'helix',
      loopDuration: 6,
      speed: 1,
      amplitude: 1,
      verticalAmplitude: 2,
      horizontalAmplitude: 1.5,
      spread: 4,
      frequency: 3,
      backgroundColor: '#000a05',
      backgroundGradientColor: '#001505',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'ripple-effect',
    name: 'Ripple Effect',
    description: 'Rippling waves of geometric shapes',
    thumbnail: '🌊',
    settings: {
      geometryType: 'plane',
      shapeCount: 15,
      shapeScale: 0.6,
      shapeColor: '#3b82f6',
      shapeColor2: '#1d4ed8',
      animationType: 'ripple',
      loopDuration: 4,
      speed: 1,
      amplitude: 1.5,
      verticalAmplitude: 2,
      horizontalAmplitude: 1,
      spread: 6,
      frequency: 2,
      backgroundColor: '#050510',
      backgroundGradientColor: '#0a0a25',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'swirl-chaos',
    name: 'Swirl Chaos',
    description: 'Chaotic swirling motion',
    thumbnail: '🌪️',
    settings: {
      geometryType: 'dodecahedron',
      shapeCount: 8,
      shapeScale: 0.5,
      shapeColor: '#ef4444',
      shapeColor2: '#dc2626',
      animationType: 'swirl',
      loopDuration: 4.5,
      speed: 1,
      amplitude: 1.7,
      verticalAmplitude: 1.8,
      horizontalAmplitude: 2,
      spread: 3.5,
      frequency: 1.8,
      backgroundColor: '#0a0000',
      backgroundGradientColor: '#1a0000',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'instagram-story-vertical',
    name: 'Instagram Story Plus',
    description: 'Optimized for Instagram Stories (vertical 9:16)',
    thumbnail: '📱',
    settings: {
      geometryType: 'torusKnot',
      shapeCount: 2,
      shapeScale: 1.2,
      shapeColor: '#ec4899',
      shapeColor2: '#06b6d4',
      animationType: 'orbit',
      loopDuration: 3,
      speed: 1,
      amplitude: 1,
      spread: 3,
      metalness: 0.8,
      roughness: 0.2,
      backgroundColor: '#0a0a0f',
      backgroundGradient: true,
      backgroundGradientColor: '#1a0a2e',
      cameraAutoRotate: false,
      exportWidth: 1080,
      exportHeight: 1920,
      exportFps: 30,
      exportFormat: 'mp4',
      exportQuality: 'excellent',
      seamlessLoopVerification: true,
    },
  },

  // ========== CRACKTRO / DEMOSCENE PRESETS ==========

  {
    id: 'cracktro-sine-scroller',
    name: 'Sine Scroller',
    description: 'Classic cracktro sine-wave scroller with metallic shapes',
    thumbnail: '📜',
    settings: {
      geometryType: 'cube',
      shapeCount: 16,
      shapeScale: 0.4,
      geometryDetail: 0,
      shapeColor: '#ff6600',
      shapeColor2: '#ffcc00',
      useGradientMaterial: true,
      wireframe: false,
      metalness: 0.9,
      roughness: 0.1,
      animationType: 'sineScroller',
      loopDuration: 6,
      speed: 1,
      amplitude: 1.5,
      spread: 5,
      frequency: 1.5,
      verticalAmplitude: 1.2,
      horizontalAmplitude: 1.5,
      rotationMultiplier: 1.5,
      cameraPreset: 'front',
      cameraDistance: 8,
      backgroundColor: '#000000',
      backgroundGradient: true,
      backgroundGradientColor: '#0a0020',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-starfield',
    name: 'Starfield',
    description: 'Classic starfield zooming through space',
    thumbnail: '✨',
    settings: {
      geometryType: 'star',
      shapeCount: 30,
      shapeScale: 0.2,
      geometryDetail: 0,
      shapeColor: '#ffffff',
      shapeColor2: '#aaaaff',
      wireframe: false,
      metalness: 0.5,
      roughness: 0.5,
      animationType: 'starfield',
      loopDuration: 5,
      speed: 1,
      amplitude: 1,
      spread: 5,
      frequency: 1,
      verticalAmplitude: 1,
      horizontalAmplitude: 1,
      rotationMultiplier: 0.5,
      cameraPreset: 'front',
      cameraDistance: 5,
      backgroundColor: '#000005',
      backgroundGradient: false,
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-copper-bars',
    name: 'Copper Bars',
    description: 'Amiga-style copper bar effect with shimmering metal',
    thumbnail: '🟫',
    settings: {
      geometryType: 'cube',
      shapeCount: 12,
      shapeScale: 0.5,
      geometryDetail: 0,
      shapeColor: '#cc4400',
      shapeColor2: '#ffaa00',
      useGradientMaterial: true,
      wireframe: false,
      metalness: 1.0,
      roughness: 0.0,
      animationType: 'copperbars',
      loopDuration: 5,
      speed: 1,
      amplitude: 2,
      spread: 4,
      frequency: 1.5,
      verticalAmplitude: 1.5,
      horizontalAmplitude: 0.5,
      rotationMultiplier: 0.2,
      cameraPreset: 'front',
      cameraDistance: 7,
      backgroundColor: '#000000',
      backgroundGradient: true,
      backgroundGradientColor: '#100008',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-bobs',
    name: 'Bobs',
    description: 'Classic demoscene "bobs" bouncing in Lissajous curves',
    thumbnail: '🔴',
    settings: {
      geometryType: 'sphere',
      shapeCount: 12,
      shapeScale: 0.5,
      geometryDetail: 2,
      shapeColor: '#ff0044',
      shapeColor2: '#4400ff',
      useGradientMaterial: true,
      wireframe: false,
      metalness: 0.8,
      roughness: 0.2,
      animationType: 'bobs',
      loopDuration: 6,
      speed: 1,
      amplitude: 1.2,
      spread: 4,
      frequency: 1.2,
      verticalAmplitude: 1,
      horizontalAmplitude: 1,
      rotationMultiplier: 2,
      cameraPreset: 'front',
      cameraDistance: 7,
      backgroundColor: '#000000',
      backgroundGradient: true,
      backgroundGradientColor: '#0a000a',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-tunnel',
    name: 'Tunnel',
    description: 'Fly through a rotating tunnel of shapes',
    thumbnail: '🕳️',
    settings: {
      geometryType: 'ring',
      shapeCount: 24,
      shapeScale: 0.5,
      geometryDetail: 1,
      shapeColor: '#00ff88',
      shapeColor2: '#0088ff',
      useGradientMaterial: true,
      wireframe: true,
      metalness: 0.6,
      roughness: 0.4,
      animationType: 'tunnel',
      loopDuration: 6,
      speed: 1,
      amplitude: 1,
      spread: 4,
      frequency: 1,
      verticalAmplitude: 1,
      horizontalAmplitude: 1,
      rotationMultiplier: 1,
      cameraPreset: 'front',
      cameraDistance: 4,
      backgroundColor: '#000000',
      backgroundGradient: true,
      backgroundGradientColor: '#000510',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-raster-bars',
    name: 'Raster Bars',
    description: 'Classic Amiga-style raster bars weaving across screen',
    thumbnail: '🌈',
    settings: {
      geometryType: 'plane',
      shapeCount: 16,
      shapeScale: 0.5,
      geometryDetail: 0,
      shapeColor: '#ff0066',
      shapeColor2: '#00ccff',
      useGradientMaterial: true,
      wireframe: false,
      metalness: 0.7,
      roughness: 0.3,
      animationType: 'rasterbars',
      loopDuration: 5,
      speed: 1,
      amplitude: 1.5,
      spread: 4,
      frequency: 2,
      verticalAmplitude: 1,
      horizontalAmplitude: 2,
      rotationMultiplier: 0.3,
      cameraPreset: 'front',
      cameraDistance: 7,
      backgroundColor: '#000000',
      backgroundGradient: false,
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-plasma',
    name: 'Plasma Grid',
    description: 'Classic plasma effect with shapes pulsing in a grid',
    thumbnail: '🟣',
    settings: {
      geometryType: 'sphere',
      shapeCount: 25,
      shapeScale: 0.4,
      geometryDetail: 1,
      shapeColor: '#ff00ff',
      shapeColor2: '#00ffff',
      useGradientMaterial: true,
      wireframe: false,
      metalness: 0.6,
      roughness: 0.4,
      animationType: 'plasma',
      loopDuration: 5,
      speed: 1,
      amplitude: 1.5,
      spread: 5,
      frequency: 1.5,
      verticalAmplitude: 1,
      horizontalAmplitude: 1,
      rotationMultiplier: 1,
      cameraPreset: 'front',
      cameraDistance: 8,
      backgroundColor: '#000005',
      backgroundGradient: true,
      backgroundGradientColor: '#05000a',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-wireframe-vector',
    name: 'Vector Demo',
    description: 'Wireframe vector object like classic Amiga/ST demos',
    thumbnail: '📐',
    settings: {
      geometryType: 'dodecahedron',
      shapeCount: 1,
      shapeScale: 2,
      geometryDetail: 0,
      shapeColor: '#00ff00',
      shapeColor2: '#00ff00',
      useGradientMaterial: false,
      wireframe: true,
      metalness: 0.2,
      roughness: 0.8,
      animationType: 'simpleRotation',
      rotationAxis: 'all',
      loopDuration: 6,
      speed: 1,
      amplitude: 1,
      spread: 2,
      frequency: 1,
      rotationMultiplier: 1,
      cameraPreset: 'front',
      cameraDistance: 5,
      backgroundColor: '#000000',
      backgroundGradient: false,
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'cracktro-glenz-vectors',
    name: 'Glenz Vectors',
    description: 'Transparent overlapping shapes like the classic Glenz effect',
    thumbnail: '💠',
    settings: {
      geometryType: 'cube',
      shapeCount: 5,
      shapeScale: 1,
      geometryDetail: 0,
      shapeColor: '#00aaff',
      shapeColor2: '#ff00aa',
      useGradientMaterial: true,
      wireframe: true,
      metalness: 0.3,
      roughness: 0.7,
      animationType: 'orbit',
      loopDuration: 5,
      speed: 1,
      amplitude: 1,
      spread: 2.5,
      frequency: 1,
      rotationMultiplier: 2,
      cameraPreset: 'front',
      cameraDistance: 6,
      backgroundColor: '#000000',
      backgroundGradient: true,
      backgroundGradientColor: '#050010',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'cracktro-dot-tunnel',
    name: 'Dot Tunnel',
    description: 'Sphere dots forming a hypnotic tunnel',
    thumbnail: '⚫',
    settings: {
      geometryType: 'sphere',
      shapeCount: 30,
      shapeScale: 0.25,
      geometryDetail: 0,
      shapeColor: '#ff8800',
      shapeColor2: '#ffff00',
      useGradientMaterial: true,
      wireframe: false,
      metalness: 0.9,
      roughness: 0.1,
      animationType: 'tunnel',
      loopDuration: 5,
      speed: 1,
      amplitude: 1,
      spread: 5,
      frequency: 1,
      verticalAmplitude: 1,
      horizontalAmplitude: 1,
      rotationMultiplier: 0.8,
      cameraPreset: 'front',
      cameraDistance: 4,
      backgroundColor: '#000000',
      backgroundGradient: false,
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-c64-style',
    name: 'C64 Cracktro',
    description: 'Commodore 64 cracktro with pixelation and retro palette',
    thumbnail: '🕹️',
    settings: {
      geometryType: 'star',
      shapeCount: 8,
      shapeScale: 0.6,
      geometryDetail: 0,
      shapeColor: '#7869c4',
      shapeColor2: '#68a941',
      wireframe: false,
      metalness: 0.3,
      roughness: 0.7,
      animationType: 'sineScroller',
      loopDuration: 6,
      speed: 1,
      amplitude: 1.5,
      spread: 5,
      frequency: 1.5,
      verticalAmplitude: 1,
      horizontalAmplitude: 1.5,
      rotationMultiplier: 1.5,
      cameraPreset: 'front',
      cameraDistance: 8,
      backgroundColor: '#40318d',
      backgroundGradient: false,
      pixelationEnabled: true,
      pixelSize: 6,
      ditheringEnabled: true,
      ditheringType: 'bayer',
      ditheringIntensity: 0.4,
      ditheringResolution: 0.3,
      paletteType: 'commodore64',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-amiga-bobs',
    name: 'Amiga Bobs',
    description: 'Classic Amiga demo bobs with golden metallic sheen',
    thumbnail: '🟡',
    settings: {
      geometryType: 'diamond',
      shapeCount: 16,
      shapeScale: 0.4,
      geometryDetail: 1,
      shapeColor: '#ffcc00',
      shapeColor2: '#ff6600',
      useGradientMaterial: true,
      wireframe: false,
      metalness: 1.0,
      roughness: 0.0,
      animationType: 'bobs',
      loopDuration: 7,
      speed: 1,
      amplitude: 1,
      spread: 4,
      frequency: 1,
      verticalAmplitude: 1,
      horizontalAmplitude: 1,
      rotationMultiplier: 3,
      cameraPreset: 'front',
      cameraDistance: 7,
      backgroundColor: '#000010',
      backgroundGradient: true,
      backgroundGradientColor: '#100020',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-kefrens-bars',
    name: 'Kefrens Bars',
    description: 'Inspired by the legendary Kefrens copper bars demo',
    thumbnail: '🔶',
    settings: {
      geometryType: 'plane',
      shapeCount: 20,
      shapeScale: 0.4,
      geometryDetail: 0,
      shapeColor: '#ff2200',
      shapeColor2: '#ffdd00',
      useGradientMaterial: true,
      wireframe: false,
      metalness: 1.0,
      roughness: 0.0,
      animationType: 'copperbars',
      loopDuration: 4,
      speed: 1,
      amplitude: 2.5,
      spread: 5,
      frequency: 2,
      verticalAmplitude: 2,
      horizontalAmplitude: 0.8,
      rotationMultiplier: 0.1,
      cameraPreset: 'front',
      cameraDistance: 8,
      backgroundColor: '#000000',
      backgroundGradient: false,
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-ascii-oldskool',
    name: 'ASCII Cracktro',
    description: 'Oldskool ASCII art cracktro with green-on-black terminal look',
    thumbnail: '🖥️',
    settings: {
      geometryType: 'torusKnot',
      shapeCount: 3,
      shapeScale: 1,
      geometryDetail: 2,
      shapeColor: '#00ff00',
      shapeColor2: '#00aa00',
      wireframe: false,
      metalness: 0.5,
      roughness: 0.5,
      animationType: 'orbit',
      loopDuration: 5,
      speed: 1,
      amplitude: 1,
      spread: 3,
      frequency: 1,
      rotationMultiplier: 1.5,
      cameraPreset: 'front',
      cameraDistance: 6,
      backgroundColor: '#000000',
      backgroundGradient: false,
      asciiEnabled: true,
      asciiCharset: 'standard',
      asciiResolution: 70,
      asciiFontSize: 14,
      asciiFontWeight: 'bold',
      asciiOpacity: 1,
      asciiBackgroundOpacity: 1,
      asciiColorMode: false,
      asciiTextColor: '#00ff00',
      asciiContrast: 1.8,
      asciiGamma: 0.7,
      asciiBrightnessBoost: 1.5,
      asciiInvert: false,
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-plasma-c64',
    name: 'C64 Plasma',
    description: 'Retro plasma effect with C64 color palette and pixelation',
    thumbnail: '🎆',
    settings: {
      geometryType: 'cube',
      shapeCount: 36,
      shapeScale: 0.35,
      geometryDetail: 0,
      shapeColor: '#ff4444',
      shapeColor2: '#4444ff',
      useGradientMaterial: true,
      wireframe: false,
      metalness: 0.4,
      roughness: 0.6,
      animationType: 'plasma',
      loopDuration: 6,
      speed: 1,
      amplitude: 2,
      spread: 6,
      frequency: 2,
      verticalAmplitude: 1,
      horizontalAmplitude: 1,
      rotationMultiplier: 0.5,
      cameraPreset: 'front',
      cameraDistance: 10,
      backgroundColor: '#000000',
      backgroundGradient: false,
      pixelationEnabled: true,
      pixelSize: 4,
      paletteType: 'commodore64',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-spectrum-twist',
    name: 'Speccy Twist',
    description: 'ZX Spectrum style with twisting wireframe shapes',
    thumbnail: '🔳',
    settings: {
      geometryType: 'icosahedron',
      shapeCount: 4,
      shapeScale: 1.2,
      geometryDetail: 1,
      shapeColor: '#ff0000',
      shapeColor2: '#00ffff',
      wireframe: true,
      metalness: 0.3,
      roughness: 0.7,
      animationType: 'twist',
      loopDuration: 5,
      speed: 1,
      amplitude: 1.2,
      spread: 3,
      frequency: 1.5,
      verticalAmplitude: 1.5,
      horizontalAmplitude: 1.8,
      rotationMultiplier: 2,
      cameraPreset: 'front',
      cameraDistance: 7,
      backgroundColor: '#000000',
      backgroundGradient: false,
      pixelationEnabled: true,
      pixelSize: 3,
      paletteType: 'zxspectrum',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'cracktro-gameboy-starfield',
    name: 'Gameboy Stars',
    description: 'Starfield effect with Gameboy green palette',
    thumbnail: '🟢',
    settings: {
      geometryType: 'diamond',
      shapeCount: 25,
      shapeScale: 0.2,
      geometryDetail: 0,
      shapeColor: '#9bbc0f',
      shapeColor2: '#0f380f',
      wireframe: false,
      metalness: 0.3,
      roughness: 0.7,
      animationType: 'starfield',
      loopDuration: 5,
      speed: 1,
      amplitude: 0.8,
      spread: 5,
      frequency: 1,
      verticalAmplitude: 1,
      horizontalAmplitude: 1,
      rotationMultiplier: 0.5,
      cameraPreset: 'front',
      cameraDistance: 5,
      backgroundColor: '#0f380f',
      backgroundGradient: false,
      pixelationEnabled: true,
      pixelSize: 4,
      paletteType: 'gameboy',
      seamlessLoopVerification: false,
    },
  },

  // ========== 3D TEXT PRESETS ==========

  {
    id: 'text-3d-chrome',
    name: '3D Chrome Text',
    description: 'Shiny chrome 3D text orbiting in space',
    thumbnail: '🔤',
    settings: {
      geometryType: 'text3d',
      textContent: 'HELLO',
      textFont: 'helvetiker_bold',
      textDepth: 0.4,
      textBevel: true,
      textBevelThickness: 0.04,
      textBevelSize: 0.03,
      shapeCount: 1,
      shapeScale: 1.2,
      shapeColor: '#c0c0c0',
      shapeColor2: '#e0e0ff',
      wireframe: false,
      metalness: 1.0,
      roughness: 0.0,
      reflectionsEnabled: true,
      animationType: 'simpleRotation',
      rotationAxis: 'y',
      loopDuration: 5,
      speed: 1,
      rotationMultiplier: 1,
      cameraPreset: 'front',
      cameraDistance: 6,
      backgroundColor: '#0a0a1a',
      backgroundGradient: true,
      backgroundGradientColor: '#1a0a2e',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'text-3d-neon',
    name: 'Neon Text',
    description: 'Glowing neon text with wireframe look',
    thumbnail: '💡',
    settings: {
      geometryType: 'text3d',
      textContent: 'NEON',
      textFont: 'optimer_bold',
      textDepth: 0.15,
      textBevel: true,
      textBevelThickness: 0.02,
      textBevelSize: 0.015,
      shapeCount: 1,
      shapeScale: 1.5,
      shapeColor: '#ff00ff',
      shapeColor2: '#00ffff',
      wireframe: true,
      metalness: 0.3,
      roughness: 0.7,
      reflectionsEnabled: false,
      animationType: 'breathe',
      loopDuration: 4,
      speed: 1,
      amplitude: 0.8,
      spread: 2,
      frequency: 1,
      rotationMultiplier: 0.5,
      cameraPreset: 'front',
      cameraDistance: 5,
      backgroundColor: '#000000',
      backgroundGradient: true,
      backgroundGradientColor: '#0a000a',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'text-3d-gold',
    name: 'Gold Text',
    description: 'Luxurious golden 3D text',
    thumbnail: '✨',
    settings: {
      geometryType: 'text3d',
      textContent: 'GOLD',
      textFont: 'gentilis_bold',
      textDepth: 0.5,
      textBevel: true,
      textBevelThickness: 0.05,
      textBevelSize: 0.04,
      shapeCount: 1,
      shapeScale: 1.3,
      shapeColor: '#ffd700',
      shapeColor2: '#ff8c00',
      wireframe: false,
      metalness: 1.0,
      roughness: 0.1,
      reflectionsEnabled: true,
      animationType: 'orbit',
      loopDuration: 6,
      speed: 1,
      amplitude: 0.5,
      spread: 2,
      rotationMultiplier: 1.5,
      cameraPreset: 'front',
      cameraDistance: 6,
      backgroundColor: '#0a0500',
      backgroundGradient: true,
      backgroundGradientColor: '#1a0f00',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'text-3d-multi-orbit',
    name: 'Text Orbit',
    description: 'Multiple text copies orbiting in 3D',
    thumbnail: '🔠',
    settings: {
      geometryType: 'text3d',
      textContent: 'SPIN',
      textFont: 'helvetiker_bold',
      textDepth: 0.2,
      textBevel: true,
      textBevelThickness: 0.02,
      textBevelSize: 0.02,
      shapeCount: 4,
      shapeScale: 0.6,
      shapeColor: '#ff4444',
      shapeColor2: '#4444ff',
      wireframe: false,
      metalness: 0.8,
      roughness: 0.2,
      reflectionsEnabled: true,
      animationType: 'orbit',
      loopDuration: 5,
      speed: 1,
      amplitude: 1,
      spread: 4,
      rotationMultiplier: 2,
      cameraPreset: 'front',
      cameraDistance: 8,
      backgroundColor: '#05050f',
      backgroundGradient: true,
      backgroundGradientColor: '#0f0520',
      seamlessLoopVerification: true,
    },
  },
  {
    id: 'text-3d-cracktro',
    name: 'Cracktro Text',
    description: 'Classic cracktro sine scroller with 3D text',
    thumbnail: '📟',
    settings: {
      geometryType: 'text3d',
      textContent: 'CRACKED',
      textFont: 'helvetiker_bold',
      textDepth: 0.15,
      textBevel: false,
      textBevelThickness: 0.02,
      textBevelSize: 0.01,
      shapeCount: 6,
      shapeScale: 0.4,
      shapeColor: '#ff6600',
      shapeColor2: '#ffcc00',
      wireframe: false,
      metalness: 0.9,
      roughness: 0.1,
      animationType: 'sineScroller',
      loopDuration: 6,
      speed: 1,
      amplitude: 1.5,
      spread: 5,
      frequency: 1.5,
      verticalAmplitude: 1.2,
      horizontalAmplitude: 1.5,
      rotationMultiplier: 2,
      cameraPreset: 'front',
      cameraDistance: 8,
      backgroundColor: '#000000',
      backgroundGradient: true,
      backgroundGradientColor: '#0a0020',
      seamlessLoopVerification: false,
    },
  },
  {
    id: 'text-3d-retro-ascii',
    name: 'ASCII Text',
    description: '3D text rendered through ASCII filter',
    thumbnail: '🖥️',
    settings: {
      geometryType: 'text3d',
      textContent: 'RETRO',
      textFont: 'droid_sans_bold',
      textDepth: 0.3,
      textBevel: true,
      textBevelThickness: 0.03,
      textBevelSize: 0.02,
      shapeCount: 1,
      shapeScale: 1.5,
      shapeColor: '#00ff00',
      shapeColor2: '#00aa00',
      wireframe: false,
      metalness: 0.5,
      roughness: 0.5,
      animationType: 'simpleRotation',
      rotationAxis: 'y',
      loopDuration: 5,
      speed: 1,
      rotationMultiplier: 1,
      cameraPreset: 'front',
      cameraDistance: 5,
      backgroundColor: '#000000',
      backgroundGradient: false,
      asciiEnabled: true,
      asciiCharset: 'standard',
      asciiResolution: 80,
      asciiFontSize: 14,
      asciiFontWeight: 'bold',
      asciiColorMode: false,
      asciiTextColor: '#00ff00',
      asciiContrast: 1.8,
      asciiGamma: 0.8,
      asciiBrightnessBoost: 1.5,
      seamlessLoopVerification: false,
    },
  },
];